package com.shverma.kinetic.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class KineticColors(
    val background: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceBright: Color,
    val outlineVariant: Color,
    val primary: Color,
    val primaryContainer: Color,
    val primaryDim: Color,
    val onPrimaryFixed: Color,
    val secondary: Color,
    val tertiary: Color,
    val error: Color,
    val onSurfaceVariant: Color,
    val onSurface: Color,
    val onPrimary: Color,
    val onSecondary: Color,
    val onTertiary: Color,
    val protein: Color,
    val carbs: Color,
    val fats: Color,
    // Confidence system — the core trust UI pattern (docs/redesign/kinetic-redesign-v1.html)
    val confidenceHighText: Color,
    val confidenceHighBase: Color,
    val confidenceHighContainer: Color,
    val confidenceMediumText: Color,
    val confidenceMediumBase: Color,
    val confidenceMediumContainer: Color,
    val confidenceLowText: Color,
    val confidenceLowBase: Color,
    val confidenceLowContainer: Color,
)

val KineticLightColors = KineticColors(
    background = RedesignLightBackground,
    surfaceContainerLowest = RedesignLightSurfaceContainerLowest,
    surfaceContainerLow = RedesignLightSurfaceContainerLow,
    surfaceContainer = RedesignLightSurfaceContainer,
    surfaceContainerHigh = RedesignLightSurfaceContainerHigh,
    surfaceContainerHighest = RedesignLightSurfaceContainerHighest,
    surfaceBright = RedesignLightSurfaceBright,
    outlineVariant = RedesignLightOutline,
    primary = RedesignLightBrand,
    primaryContainer = RedesignLightBrand,
    primaryDim = RedesignLightBrand,
    onPrimaryFixed = RedesignLightOnBrand,
    secondary = RedesignLightBrand,
    tertiary = RedesignConfidenceLowBaseLight,
    error = RedesignConfidenceLowTextLight,
    onSurfaceVariant = RedesignLightOnSurfaceVariant,
    onSurface = RedesignLightOnSurface,
    onPrimary = RedesignLightOnBrand,
    onSecondary = RedesignLightOnBrand,
    onTertiary = RedesignLightOnBrand,
    protein = RedesignLightBrand,
    carbs = RedesignLightBrand,
    fats = RedesignLightBrand,
    confidenceHighText = RedesignConfidenceHighTextLight,
    confidenceHighBase = RedesignConfidenceHighBaseLight,
    confidenceHighContainer = RedesignConfidenceHighContainerLight,
    confidenceMediumText = RedesignConfidenceMediumTextLight,
    confidenceMediumBase = RedesignConfidenceMediumBaseLight,
    confidenceMediumContainer = RedesignConfidenceMediumContainerLight,
    confidenceLowText = RedesignConfidenceLowTextLight,
    confidenceLowBase = RedesignConfidenceLowBaseLight,
    confidenceLowContainer = RedesignConfidenceLowContainerLight,
)

val KineticDarkColors = KineticColors(
    background = RedesignDarkBackground,
    surfaceContainerLowest = RedesignDarkSurfaceContainerLowest,
    surfaceContainerLow = RedesignDarkSurfaceContainerLow,
    surfaceContainer = RedesignDarkSurfaceContainer,
    surfaceContainerHigh = RedesignDarkSurfaceContainerHigh,
    surfaceContainerHighest = RedesignDarkSurfaceContainerHighest,
    surfaceBright = RedesignDarkSurfaceBright,
    outlineVariant = RedesignDarkOutline,
    primary = RedesignDarkBrand,
    primaryContainer = RedesignDarkBrand,
    primaryDim = RedesignDarkBrand,
    onPrimaryFixed = RedesignDarkOnBrand,
    secondary = RedesignDarkBrand,
    tertiary = RedesignConfidenceLowBaseDark,
    error = RedesignConfidenceLowTextDark,
    onSurfaceVariant = RedesignDarkOnSurfaceVariant,
    onSurface = RedesignDarkOnSurface,
    onPrimary = RedesignDarkOnBrand,
    onSecondary = RedesignDarkOnBrand,
    onTertiary = RedesignDarkOnBrand,
    protein = RedesignDarkBrand,
    carbs = RedesignDarkBrand,
    fats = RedesignDarkBrand,
    confidenceHighText = RedesignConfidenceHighTextDark,
    confidenceHighBase = RedesignConfidenceHighBaseDark,
    confidenceHighContainer = RedesignConfidenceHighContainerDark,
    confidenceMediumText = RedesignConfidenceMediumTextDark,
    confidenceMediumBase = RedesignConfidenceMediumBaseDark,
    confidenceMediumContainer = RedesignConfidenceMediumContainerDark,
    confidenceLowText = RedesignConfidenceLowTextDark,
    confidenceLowBase = RedesignConfidenceLowBaseDark,
    confidenceLowContainer = RedesignConfidenceLowContainerDark,
)

val LocalKineticColors = staticCompositionLocalOf<KineticColors> {
    error("No KineticColors provided — wrap your UI in KineticTheme { }")
}
