package com.shverma.kinetic.data.repository

import com.shverma.kinetic.data.local.entity.FoodEntity
import com.shverma.kinetic.data.model.ai.AIFoodItem
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class FoodResolver @Inject constructor(
    private val localDataSource: LocalFoodDataSource,
    private val remoteDataSource: FirebaseFoodDataSource,
    private val aiDataSource: AINutritionDataSource
) {

    companion object {
        private const val TAG = "FoodResolver"
    }

    fun resolve(input: String): String {
        return input.lowercase()
            .trim()
            .replace("sabji", "")
            .replace("curry", "")
            .replace("masala", "")
            .replace("gravy", "")
            .trim()
    }

    private fun FoodEntity.hasValidMacros(): Boolean {
        return caloriesPer100g > 0 || proteinPer100g > 0 || carbsPer100g > 0 || fatsPer100g > 0
    }

    fun resolveFoods(items: List<AIFoodItem>): Flow<Map<String, FoodEntity>> = flow {
        val result = mutableMapOf<String, FoodEntity>()
        val normalizedItems = items.map { resolve(it.food) }

        Timber.d("resolveFoods: Resolving items: $normalizedItems")

        // 1. Local Database
        val localFoods = localDataSource.getFoodsByNames(normalizedItems)
        val nameToLocalId = mutableMapOf<String, Int>()
        localFoods.forEach {
            if (it.hasValidMacros()) {
                result[it.name] = it
                Timber.v("resolveFoods: Found locally with valid macros: ${it}")
            } else {
                nameToLocalId[it.name] = it.foodId
                Timber.v("resolveFoods: Found locally but invalid macros: ${it.name}")
            }
        }
        // Emit initial results from local DB
        emit(result.toMap())

        val missing = normalizedItems.filterNot { result.containsKey(it) }
        if (missing.isEmpty()) return@flow

        // 2. Firestore/Remote
        Timber.d("resolveFoods: Fetching from Firestore: $missing")
        val firestoreFoods = remoteDataSource.fetchFoodsBatch(missing)
        var firestoreUpdated = false
        firestoreFoods.forEach {
            if (it.hasValidMacros()) {
                val foodToSave = if (nameToLocalId.containsKey(it.name)) {
                    it.copy(foodId = nameToLocalId[it.name]!!)
                } else it

                // If foodId is still 0, it will be auto-generated by local DB
                val savedId = localDataSource.saveFood(foodToSave)
                val finalFood = if (foodToSave.foodId == 0) foodToSave.copy(foodId = savedId) else foodToSave

                // Update Firestore if we generated a new ID
                if (foodToSave.foodId == 0) {
                    remoteDataSource.saveFood(finalFood)
                }

                result[it.name] = finalFood
                firestoreUpdated = true
                Timber.v("resolveFoods: Found on Firestore: ${finalFood}")
            }
        }

        // Emit if we found anything on Firestore
        if (firestoreUpdated) {
            emit(result.toMap())
        }

        val stillMissing = missing.filterNot { result.containsKey(it) }
        if (stillMissing.isEmpty()) return@flow

        // 3. AI Nutrition Estimation
        Timber.d("resolveFoods: Estimating via AI for: $stillMissing")
        val aiEntities = aiDataSource.estimateNutrition(stillMissing)
        if (aiEntities.isNotEmpty()) {
            aiEntities.forEach { entity ->
                val foodToSave = if (nameToLocalId.containsKey(entity.name)) {
                    entity.copy(foodId = nameToLocalId[entity.name]!!)
                } else entity

                val savedId = localDataSource.saveFood(foodToSave)
                val finalFood = if (foodToSave.foodId == 0) foodToSave.copy(foodId = savedId) else foodToSave

                // If it's a new food (foodId was 0), save to Firestore as well
                if (foodToSave.foodId == 0) {
                    remoteDataSource.saveFood(finalFood)
                }

                result[entity.name] = finalFood
                Timber.v("resolveFoods: Estimated via AI: ${finalFood}")
            }
            // Final emission with AI results
            emit(result.toMap())
        }
    }
}